/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ClienteDAO;
import controller.ControllerClienteTexto;
import controller.ControllerClienteBinario;
import javax.swing.JOptionPane;
import model.Cliente;

/**
 *
 * @author andre
 */
public class CadastrarClienteView extends javax.swing.JFrame {

    //Controllers
    private ControllerClienteTexto ct = new ControllerClienteTexto();
    private ControllerClienteBinario cb = new ControllerClienteBinario();
    private ClienteDAO cd = new ClienteDAO();
    
    //Labels
    public static final int TEXT = 1;
    public static final int BINARY = 2;
    public static final int DATABASE = 3;
    private int mode;

    public CadastrarClienteView(int whereToSearch) {
        this.mode = whereToSearch;
        System.out.println("Entrando em modo " + mode);
        initComponents();
        this.setDefaultCloseOperation(CadastrarClienteView.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileTypeGroup = new javax.swing.ButtonGroup();
        Menu = new javax.swing.JInternalFrame();
        MenuInterno = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cpfF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomeF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sobrenomeF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        valorF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        idadeF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cadastrarButton = new javax.swing.JButton();
        voltarB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setVisible(true);

        MenuInterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("CPF");

        jLabel2.setText("Nome");

        jLabel3.setText("Sobrenome");

        jLabel4.setText("Valor gasto");

        jLabel5.setText("Idade");

        jLabel7.setText("Cadastro de cliente");

        javax.swing.GroupLayout MenuInternoLayout = new javax.swing.GroupLayout(MenuInterno);
        MenuInterno.setLayout(MenuInternoLayout);
        MenuInternoLayout.setHorizontalGroup(
            MenuInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuInternoLayout.createSequentialGroup()
                .addGroup(MenuInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuInternoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MenuInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuInternoLayout.createSequentialGroup()
                                .addGroup(MenuInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MenuInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuInternoLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(49, 49, 49)))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(17, 17, 17)
                                .addGroup(MenuInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idadeF, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                                    .addComponent(valorF)
                                    .addComponent(sobrenomeF)
                                    .addComponent(nomeF)
                                    .addComponent(cpfF)))
                            .addComponent(jLabel5)))
                    .addGroup(MenuInternoLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuInternoLayout.setVerticalGroup(
            MenuInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuInternoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(MenuInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cpfF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sobrenomeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(MenuInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(idadeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cadastrarButtonMousePressed(evt);
            }
        });

        voltarB.setText("Voltar");
        voltarB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                voltarBMousePressed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu.getContentPane());
        Menu.getContentPane().setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MenuInterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addComponent(cadastrarButton)
                        .addGap(274, 274, 274)
                        .addComponent(voltarB, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(MenuInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarButton)
                    .addComponent(voltarB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarButtonMousePressed
        if(ControllerClienteTexto.CFile.getArquivo() != null || ControllerClienteBinario.BFile.getArquivo() != null || cd.checkConnection()){
           cadastraInfo(); 
        }else{
            JOptionPane.showMessageDialog(this, "Selecione um arquivo!!!", "Arquivo não encontrado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cadastrarButtonMousePressed

    private void voltarBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarBMousePressed
        TelaInicialView ti = new TelaInicialView();
        ti.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarBMousePressed


    private void cadastraInfo() {
        switch (this.mode) {
            case TEXT -> cadastraClienteTexto();
            case BINARY -> cadastraClienteBinario();
            case DATABASE -> cadastraClienteDB();
            default -> JOptionPane.showMessageDialog(this, "Ocorreu um problema inesperado", "Problema inesperado", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cadastraClienteDB(){
        try{      
            if(cd.inserir(field2object())){
                JOptionPane.showMessageDialog(this, "Usuário salvo com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                cd.commit();
            }else{
                JOptionPane.showMessageDialog(this, "Cliente já existe. Impossível cadastrar ID duplicado", "Erro", JOptionPane.ERROR_MESSAGE);
                cd.rollback();
            }
        }catch(NumberFormatException nfe){        
            JOptionPane.showMessageDialog(this, "Informação inválida nos campos", "Erro", JOptionPane.ERROR_MESSAGE);
            cd.rollback();
        }
    }
    
    public void cadastraClienteBinario() {
        try {
            if (ControllerClienteBinario.BFile.getArquivo() != null) {
                Cliente cliente = cb.createCliente(Long.parseLong(cpfF.getText()),
                        nomeF.getText(),
                        sobrenomeF.getText(), Integer.parseInt(idadeF.getText()),
                        Float.parseFloat(valorF.getText()));
                
                ControllerClienteBinario.BFile.setObject(cliente);
                System.out.println(((Cliente)ControllerClienteBinario.BFile.getObject()).getNome());
                ControllerClienteBinario.BFile.escrever(true);
                JOptionPane.showMessageDialog(this, "Usuário salvo com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um arquivo!!!", "Arquivo não encontrado", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Informação inválida nos campos", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void cadastraClienteTexto() {
        if (ControllerClienteTexto.CFile.isHasAFile()) {
            try {
                ct.setCliente(Long.parseLong(cpfF.getText()), nomeF.getText(),
                        sobrenomeF.getText(), Integer.parseInt(idadeF.getText()),
                        Float.parseFloat(valorF.getText()));

                ct.salvar();
                JOptionPane.showMessageDialog(this, "Usuário salvo com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Informação inválida nos campos", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um arquivo!!!", "Arquivo não encontrado", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private Cliente field2object(){
        Cliente cli = new Cliente(Long.parseLong(cpfF.getText()), nomeF.getText(),
                        sobrenomeF.getText(), Integer.parseInt(idadeF.getText()),
                        Float.parseFloat(valorF.getText()));
        return cli;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame Menu;
    private javax.swing.JPanel MenuInterno;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JTextField cpfF;
    private javax.swing.ButtonGroup fileTypeGroup;
    private javax.swing.JTextField idadeF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nomeF;
    private javax.swing.JTextField sobrenomeF;
    private javax.swing.JTextField valorF;
    private javax.swing.JButton voltarB;
    // End of variables declaration//GEN-END:variables
}
