/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerFornecedorBinario;
import controller.ControllerFornecedorTexto;
import controller.FornecedorDAO;
import javax.swing.JOptionPane;
import model.Fornecedor;

/**
 *
 * @author andre
 */
public class ProcurarFornecedorView extends javax.swing.JFrame {

    //Controllers
    private ControllerFornecedorTexto ft = new ControllerFornecedorTexto();
    private ControllerFornecedorBinario fb = new ControllerFornecedorBinario();
    private FornecedorDAO fd = new FornecedorDAO();

    //Labels
    public static final int TEXT = 1;
    public static final int BINARY = 2;
    public static final int DATABASE = 3;
    private int mode;

    public ProcurarFornecedorView(int whereToSearch) {
        this.mode = whereToSearch;
        System.out.println("Entrando em modo " + mode);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileButton = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeF = new javax.swing.JTextField();
        categoriaF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        idF = new javax.swing.JTextField();
        buscarB = new javax.swing.JButton();
        voltarB = new javax.swing.JButton();
        salvarB = new javax.swing.JButton();
        removerB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Nome");

        jLabel3.setText("Categoria");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeF, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriaF, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("ID");

        buscarB.setText("Buscar");
        buscarB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarBMousePressed(evt);
            }
        });

        voltarB.setText("Voltar");
        voltarB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                voltarBMousePressed(evt);
            }
        });

        salvarB.setText("Salvar alterações");
        salvarB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salvarBMousePressed(evt);
            }
        });

        removerB.setText("Remover");
        removerB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removerBMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(salvarB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removerB)
                        .addGap(82, 82, 82)
                        .addComponent(voltarB))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idF, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(buscarB)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarB)
                    .addComponent(removerB)
                    .addComponent(salvarB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBMousePressed
        if (ControllerFornecedorTexto.CFile.getArquivo() != null || fb.BFile.getArquivo() != null || fd.checkConnection()) {
            buscar();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um arquivo!!!", "Arquivo não encontrado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buscarBMousePressed

    private void voltarBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarBMousePressed
        TelaInicialView ti = new TelaInicialView();
        ti.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarBMousePressed

    private void salvarBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarBMousePressed
        if (ControllerFornecedorTexto.CFile.getArquivo() != null || ControllerFornecedorBinario.BFile.getArquivo() != null || fd.checkConnection()) {
            alterar();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um arquivo!!!", "Arquivo não encontrado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_salvarBMousePressed

    private void removerBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removerBMousePressed
        if (ControllerFornecedorTexto.CFile.getArquivo() != null || ControllerFornecedorBinario.BFile.getArquivo() != null || fd.checkConnection()) {
            remover();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um arquivo!!!", "Arquivo não encontrado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_removerBMousePressed

    private void buscar() {
        switch (this.mode) {
            case TEXT -> {
                try {
                    String[] resultado = ft.buscar(Integer.parseInt(idF.getText()));
                    if (resultado != null) {
                        nomeF.setText(resultado[1]);
                        categoriaF.setText(resultado[2]);
                    } else {
                        nomeF.setText("");
                        categoriaF.setText("");
                        JOptionPane.showMessageDialog(this, "Fornecedor não encontado!!!", "Não encontrado", JOptionPane.INFORMATION_MESSAGE);

                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Formato inválido", "Inválido", JOptionPane.ERROR_MESSAGE);
                }
            }
            case BINARY -> {
                Fornecedor forn = fb.buscar(Integer.parseInt(idF.getText()));
                if (forn != null && ControllerFornecedorBinario.BFile != null) {
                    idF.setText(String.valueOf(forn.getId()));
                    nomeF.setText(forn.getNome());
                    categoriaF.setText(forn.getCategoria());
                } else {
                    nomeF.setText("");
                    categoriaF.setText("");
                    JOptionPane.showMessageDialog(this, "Fornecedor não encontado!!!", "Não encontrado", JOptionPane.INFORMATION_MESSAGE);

                }
            }
            case DATABASE -> {
                Fornecedor forn = fd.buscar(Integer.parseInt(idF.getText()));
                if (forn != null) {
                    idF.setText(String.valueOf(forn.getId()));
                    nomeF.setText(forn.getNome());
                    categoriaF.setText(forn.getCategoria());
                } else {
                    nomeF.setText("");
                    categoriaF.setText("");
                    JOptionPane.showMessageDialog(this, "Fornecedor não encontado!!!", "Não encontrado", JOptionPane.INFORMATION_MESSAGE);

                }
            }
            default -> {
                JOptionPane.showMessageDialog(this, "Algo deu errado!!!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void alterar() {
        try {

            switch (this.mode) {
                case TEXT -> {
                    String[] result = ft.buscar(Integer.parseInt(idF.getText()));
                    if (result != null) {
                        String[] novaInfo = (idF.getText() + ';' + nomeF.getText() + ';' + categoriaF.getText()).split(";");
                        if (ControllerFornecedorTexto.CFile.atualizaLinha(result, novaInfo, ft.getLinha())) {
                            JOptionPane.showMessageDialog(this, "Dados atualizados!!!", "Atualização", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(this, "Algo deu errado!!!", "Erro", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Objeto não existente. Impossível alterar", "Erro", JOptionPane.ERROR_MESSAGE);
                    }

                }
                case BINARY -> {
                    if (fb.alterar(fb.createFornecedor(Integer.parseInt(idF.getText()),
                            nomeF.getText(), categoriaF.getText()))) {
                        JOptionPane.showMessageDialog(this, "Dados atualizados!!!", "Atualização", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Objeto não existente. Impossível alterar", "Erro", JOptionPane.ERROR_MESSAGE);
                    }

                }
                case DATABASE -> {
                    if (fd.alterar(field2object(), Integer.parseInt(idF.getText()))) {
                        JOptionPane.showMessageDialog(this, "Dados atualizados!!!", "Atualização", JOptionPane.INFORMATION_MESSAGE);
                        fd.commit();
                    } else {
                        JOptionPane.showMessageDialog(this, "Objeto não existente. Impossível alterar", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                    fd.rollback();
                }
                default -> {
                    JOptionPane.showMessageDialog(this, "Algo deu errado!!!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Informações inválidas nos campos", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private Fornecedor field2object() {
        Fornecedor newF = new Fornecedor(Integer.parseInt(idF.getText()),
                nomeF.getText(), categoriaF.getText());
        return newF;
    }

    private void remover() {
        switch (this.mode) {
            case TEXT -> {
                String[] result = ft.buscar(Integer.parseInt(idF.getText()));
                String[] novaInfo = "".split(";");
                if (ControllerFornecedorTexto.CFile.atualizaLinha(result, novaInfo, ft.getLinha())) {
                    idF.setText("");
                    nomeF.setText("");
                    categoriaF.setText("");
                    JOptionPane.showMessageDialog(this, "Dados Removidos!!!", "Atualização", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Algo deu errado!!!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }

            case BINARY -> {
                if (fb.remover(Integer.parseInt(idF.getText()))) {
                    JOptionPane.showMessageDialog(this, "Dados Removidos!!!", "Atualização", JOptionPane.INFORMATION_MESSAGE);
                    idF.setText("");
                    nomeF.setText("");
                    categoriaF.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Algo deu errado!!!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
            case DATABASE -> {
                if (fd.excluir(Integer.parseInt(idF.getText()))) {
                    JOptionPane.showMessageDialog(this, "Dados Removidos!!!", "Atualização", JOptionPane.INFORMATION_MESSAGE);
                    idF.setText("");
                    nomeF.setText("");
                    categoriaF.setText("");
                    fd.commit();
                } else {
                    JOptionPane.showMessageDialog(this, "Algo deu errado!!!", "Erro", JOptionPane.ERROR_MESSAGE);
                    fd.rollback();
                }

            }
            default -> {
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarB;
    private javax.swing.JTextField categoriaF;
    private javax.swing.ButtonGroup fileButton;
    private javax.swing.JTextField idF;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeF;
    private javax.swing.JButton removerB;
    private javax.swing.JButton salvarB;
    private javax.swing.JButton voltarB;
    // End of variables declaration//GEN-END:variables
}
